// Country data from Almanique.xlsx
// This file contains information about 195 countries with 12 metrics each
// eslint-disable-next-line no-unused-vars
const countriesData = [
  {
    "country": "Afghanistan",
    "capital": "Kabul",
    "population": 44515793,
    "gdp": "17.23 billion (USD)",
    "area": "652.867 km2",
    "coordinates": "33.9391 N, 67.7100 E",
    "official_languages": "Pashto, Dari",
    "currency": "Afghani",
    "country_code": "+93",
    "religion": "Islam",
    "elevation": "1,791 m",
    "gold_reserves": "21.87 tonnes"
  },
  {
    "country": "Albania",
    "capital": "Tirana",
    "population": 2771508,
    "gdp": "27.18 billion (USD)",
    "area": "28,748 km2",
    "coordinates": "41.1533 N, 20.1683 E",
    "official_languages": "Albanian",
    "currency": "Lek",
    "country_code": "+355",
    "religion": "Islam",
    "elevation": "708 m",
    "gold_reserves": "3.42 t"
  },
  {
    "country": "Algeria",
    "capital": "Algiers",
    "population": 47834661,
    "gdp": "264.91 billion(USD)",
    "area": "2,381,741 km2",
    "coordinates": "28.0339 N 1.6596 E",
    "official_languages": "Arabic, Tamazight",
    "currency": "Algerian Dinar (DZD)",
    "country_code": "+213",
    "religion": "Islam",
    "elevation": "800 m",
    "gold_reserves": "173.56 Tonnes"
  },
  {
    "country": "Andorra",
    "capital": "Andorra La Vella",
    "population": 80578,
    "gdp": "6.00 billion (USD)",
    "area": "67.63 km2",
    "coordinates": "42.5063 N 1.5218 E",
    "official_languages": "Catalan",
    "currency": "Euro (EUR)",
    "country_code": "+376",
    "religion": "Christianity",
    "elevation": "1,996 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Angola",
    "capital": "Luanda",
    "population": 39040039,
    "gdp": "80.40 billion (USD)",
    "area": "1,246,700 km2",
    "coordinates": "11.2027 S 17.8739 E",
    "official_languages": "Portuguese",
    "currency": "Angolan Kwanza (AOA",
    "country_code": "+244",
    "religion": "Christianity",
    "elevation": "1,112 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Antigua and Barbuda",
    "capital": "Saint John's",
    "population": 95319,
    "gdp": "2.22 billion (USD)",
    "area": "281 km2",
    "coordinates": "17.0608 N 61.7964 W",
    "official_languages": "English",
    "currency": "East Caribbean Dollar (XCD)",
    "country_code": "+1-268",
    "religion": "Christianity",
    "elevation": "21 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Argentina",
    "capital": "Buenos Aires",
    "population": 45851378,
    "gdp": "632.15 billion (USD)",
    "area": "2,780,400 km2",
    "coordinates": "38.4161 S 63.6167 W",
    "official_languages": "Spanish",
    "currency": "Argentine Peso(ARS)",
    "country_code": "+54",
    "religion": "Christianity",
    "elevation": "595 m",
    "gold_reserves": "61.74 Tonnes"
  },
  {
    "country": "Armenia",
    "capital": "Yerevan",
    "population": 2952365,
    "gdp": "25.79 billion (USD)",
    "area": "29,743 km2",
    "coordinates": "40.0691 N 45.0382 E",
    "official_languages": "Armentian",
    "currency": "Armenian Dram (AMD)",
    "country_code": "+374",
    "religion": "Christianity",
    "elevation": "1,792 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Australia",
    "capital": "Canberra",
    "population": 26974026,
    "gdp": "1,752.19 billion (USD)",
    "area": "7,692,024 km2",
    "coordinates": "25.2744 S 133.7751 E",
    "official_languages": "English",
    "currency": "Australian Dollar (AUD)",
    "country_code": "+61",
    "religion": "Christianity",
    "elevation": "330 m",
    "gold_reserves": "79.87 Tonnes"
  },
  {
    "country": "Austria",
    "capital": "Vienna",
    "population": 9113574,
    "gdp": "521.64 billion (USD)",
    "area": "83,879 km2",
    "coordinates": "47.5162 N 14.5501 E",
    "official_languages": "German",
    "currency": "Euro (EUR)",
    "country_code": "+43",
    "religion": "Christianity",
    "elevation": "910 m",
    "gold_reserves": "279.99 Tonnes"
  },
  {
    "country": "Azerbaijan",
    "capital": "Baku",
    "population": 10397713,
    "gdp": "74.32 billion (USD)",
    "area": "86,600 km2",
    "coordinates": "40.1431 N 47.5769 E",
    "official_languages": "Azerbaijani",
    "currency": "Azerbaijani Manat (AZN)",
    "country_code": "+994",
    "religion": "Islam",
    "elevation": "384 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Bahamas",
    "capital": "Nassau",
    "population": 403033,
    "gdp": "15.83 billion (USD)",
    "area": "13,878 km2",
    "coordinates": "25.0343 N 77.3963 W",
    "official_languages": "English",
    "currency": "Bahamian Dollar (BSD)",
    "country_code": "+1-242",
    "religion": "Christianity",
    "elevation": "30 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Bahrain",
    "capital": "Manama",
    "population": 1511676,
    "gdp": "47.74 billion (USD)",
    "area": "785 km2",
    "coordinates": "26.0667 N 50.5577 E",
    "official_languages": "Arabic",
    "currency": "Bahraini Dinar (BHD)",
    "country_code": "+973",
    "religion": "Islam",
    "elevation": "61 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Bangladesh",
    "capital": "Dhaka",
    "population": 175686899,
    "gdp": "450.12 billion (USD)",
    "area": "147,570 km2",
    "coordinates": "23.6850 N 90.3563 E",
    "official_languages": "Bengali",
    "currency": "Bangladeshi Taka (BDT)",
    "country_code": "+880",
    "religion": "Islam",
    "elevation": "85 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Barbados",
    "capital": "Bridgetown",
    "population": 282623,
    "gdp": "7.17 billion (USD)",
    "area": "439 km2",
    "coordinates": "13.1939 N 59.5432 W",
    "official_languages": "English",
    "currency": "Barbadian Dollar (BBD)",
    "country_code": "+1-246",
    "religion": "Christianity",
    "elevation": "180-240 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Belarus",
    "capital": "Minsk",
    "population": 8997603,
    "gdp": "75.3 billion (USD)",
    "area": "207,600 km2",
    "coordinates": "53.7098 N 27.9534 E",
    "official_languages": "Belarusian, Russian",
    "currency": "Belarusian Ruble (BYN)",
    "country_code": "+387",
    "religion": "Christianity",
    "elevation": "160 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Belgium",
    "capital": "Brussels",
    "population": 11758603,
    "gdp": "664.56 billion (USD)",
    "area": "30,689 km2",
    "coordinates": "50.5039 N 4.4699 E",
    "official_languages": "Dutch, French, German",
    "currency": "Euro (EUR)",
    "country_code": "+32",
    "religion": "Christianity",
    "elevation": "181 m",
    "gold_reserves": "227 Tonnes"
  },
  {
    "country": "Belize",
    "capital": "Belmopen",
    "population": 420511,
    "gdp": "3.52 billion (USD)",
    "area": "22,966 km2",
    "coordinates": "17.1899 N 88.4976 W",
    "official_languages": "English",
    "currency": "Belize Dollar (BZD)",
    "country_code": "+501",
    "religion": "Christianity",
    "elevation": "173 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Benin",
    "capital": "Porto-Novo",
    "population": 14814460,
    "gdp": "21.48 billion (USD)",
    "area": "112,622 km2",
    "coordinates": "9.3077 N 2.3158 E",
    "official_languages": "French",
    "currency": "West African CFA Franc (XOF)",
    "country_code": "+229",
    "religion": "Christianity",
    "elevation": "200 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Bhutan",
    "capital": "Sucre",
    "population": 782460,
    "gdp": "3.09 billion (USD)",
    "area": "38,394 km2",
    "coordinates": "27.5142 N 90.4336 E",
    "official_languages": "Dzongkha",
    "currency": "Indian Rupee, Bhutanese",
    "country_code": "+975",
    "religion": "Buddhism",
    "elevation": "",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Bolivia",
    "capital": "Sucre/LaPaz",
    "population": 12581843,
    "gdp": "48.40 billion (USD)",
    "area": "1,098,581 km2",
    "coordinates": "16.2902 S 63.5887 W",
    "official_languages": "Spanish",
    "currency": "Bolivian Boliviano (BOB)",
    "country_code": "+591",
    "religion": "Christianity",
    "elevation": "1,192 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Bosnia and Herzegovina",
    "capital": "Sarajevo",
    "population": 3140095,
    "gdp": "28.34 billion (USD)",
    "area": "51,209 km2",
    "coordinates": "43.9159 N 17.6791 E",
    "official_languages": "Bosnian, Crotian, Serbian",
    "currency": "Bosnia-Herzegovina Convertible Mark (BAM)",
    "country_code": "+387",
    "religion": "Islam",
    "elevation": "500 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Botswana",
    "capital": "Gaborone",
    "population": 2562122,
    "gdp": "19.36 billion (USD)",
    "area": "581,730 km2",
    "coordinates": "22.3285 S 24.6849 E",
    "official_languages": "English, Setswana",
    "currency": "Botswanan Pula (BWP)",
    "country_code": "+267",
    "religion": "Christianity",
    "elevation": "1,013 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Brazil",
    "capital": "Brasilia",
    "population": 212812405,
    "gdp": "2,179.41 billion (USD)",
    "area": "8,514,215 km2",
    "coordinates": "14.2350 S 51.9253 W",
    "official_languages": "Portuguese",
    "currency": "Brazilian Real (BRL)",
    "country_code": "+55",
    "religion": "Christianity",
    "elevation": "320 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Brunei",
    "capital": "Bander Seri Begawan",
    "population": 466330,
    "gdp": "15.46 billion (USD)",
    "area": "5,765 km2",
    "coordinates": "4.5353 N 114.7277 E",
    "official_languages": "Malay",
    "currency": "Brunei Dollar (BND)",
    "country_code": "+673",
    "religion": "Islam",
    "elevation": "478 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Bulgaria",
    "capital": "Sofia",
    "population": 6732203,
    "gdp": "112.23 billion(USD)",
    "area": "110,994 km2",
    "coordinates": "42.7339 N 25.44858 E",
    "official_languages": "Bulgarian",
    "currency": "Bulgarian Lev (BGN)",
    "country_code": "+359",
    "religion": "Christianity",
    "elevation": "472 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Burkina Faso",
    "capital": "Ouagadougou",
    "population": 24074580,
    "gdp": "23.98 billion (USD)",
    "area": "274,200 km2",
    "coordinates": "12.2383 N 1.5616 W",
    "official_languages": "French",
    "currency": "West African CFA franc (XOF)",
    "country_code": "+226",
    "religion": "Islam",
    "elevation": "297 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Burundi",
    "capital": "Gitega",
    "population": 13948140,
    "gdp": "6.75 billion (USD)",
    "area": "25,680 km2",
    "coordinates": "3.3731 S 29.9189 E",
    "official_languages": "Kirundi,French,English",
    "currency": "Burundian Franc (BIF)",
    "country_code": "+257",
    "religion": "Christianity",
    "elevation": "1,504 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Cote d'Ivoire",
    "capital": "Yamoussoukro",
    "population": 32711547,
    "gdp": "86.56 billion (USD)",
    "area": "322,462 km2",
    "coordinates": "7.5400 N 5.5471 W",
    "official_languages": "French",
    "currency": "West African CFA franc",
    "country_code": "+225",
    "religion": "Islam",
    "elevation": "250 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Cabo Verde",
    "capital": "Praia",
    "population": 527326,
    "gdp": "2.73 billion (USD)",
    "area": "4,033 km2",
    "coordinates": "16.5388 N 23.0418 W",
    "official_languages": "Portuguese",
    "currency": "Cape Verdean Escudo",
    "country_code": "+238",
    "religion": "Christianity",
    "elevation": "1,415 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Cambodia",
    "capital": "Phnom Penh",
    "population": 17847982,
    "gdp": "47.33 billion (USD)",
    "area": "181,035 km2",
    "coordinates": "12.5657 N 104.9910 E",
    "official_languages": "Khmer",
    "currency": "Cambodian Riel (KHR)",
    "country_code": "+855",
    "religion": "Buddhism",
    "elevation": "126 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Cameroon",
    "capital": "Yaounde",
    "population": 30150781,
    "gdp": "52.78 billion (USD)",
    "area": "475,442 km2",
    "coordinates": "7.3697 N 12.3547 E",
    "official_languages": "French,English",
    "currency": "Central African CFA franc (XAF)",
    "country_code": "+237",
    "religion": "Christianity",
    "elevation": "667 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Canada",
    "capital": "Ottawa",
    "population": 41695000,
    "gdp": "2.39 trillion (USD)",
    "area": "9,984,670 km2",
    "coordinates": "56.1304 N 106.3468 W",
    "official_languages": "English, French",
    "currency": "Canadian Dollar (CAD)",
    "country_code": "+1",
    "religion": "Christianity",
    "elevation": "487 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Car",
    "capital": "Bangui",
    "population": 6097449,
    "gdp": "2.321 billion(USD)",
    "area": "622,984 km2",
    "coordinates": "6.6111 N 20.9394 E",
    "official_languages": "French, Sango",
    "currency": "CFA franc",
    "country_code": "+236",
    "religion": "Islam",
    "elevation": "635 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Chad",
    "capital": "N'Djamena",
    "population": 19425960,
    "gdp": "13.15 billion (USD)",
    "area": "1,284,000 km2",
    "coordinates": "15.4542 N 18.7322 E",
    "official_languages": "French, Arabic",
    "currency": "Central Afican CFA franc (XAF)",
    "country_code": "+235",
    "religion": "Islam",
    "elevation": "543",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Chile",
    "capital": "Santiago",
    "population": 19859921,
    "gdp": "330.27 billion (USD)",
    "area": "756,096 km2",
    "coordinates": "35.6751 S 71.5430 W",
    "official_languages": "Spanish",
    "currency": "Chilian Peso (CLP)",
    "country_code": "+56",
    "religion": "Christianity",
    "elevation": "1,871 m",
    "gold_reserves": "0.25 Tonnes"
  },
  {
    "country": "China",
    "capital": "Beijing",
    "population": 1416096094,
    "gdp": "19.53 trillion USD",
    "area": "9,596,960 km2",
    "coordinates": "35.8617 N 104.1954 E",
    "official_languages": "Mandarin",
    "currency": "Chinese Yuan (CNY)",
    "country_code": "+86",
    "religion": "Buddhism",
    "elevation": "1,840 m",
    "gold_reserves": "2,264.32 Tonnes"
  },
  {
    "country": "Colombia",
    "capital": "Bogota",
    "population": 53425635,
    "gdp": "418.54 billion (USD)",
    "area": "1,141,748 km2",
    "coordinates": "4.5709 N 74.2973 W",
    "official_languages": "Spanish",
    "currency": "Colombian Peso (COP)",
    "country_code": "+57",
    "religion": "Christianity",
    "elevation": "593 m",
    "gold_reserves": "4.68 Tonnes"
  },
  {
    "country": "Comoros",
    "capital": "Moroni",
    "population": 883075,
    "gdp": "1.55 billion (USD)",
    "area": "1,659 km2",
    "coordinates": "11.6455 S 43.3333 E",
    "official_languages": "French,Arabic",
    "currency": "Comorian Franc",
    "country_code": "+269",
    "religion": "Islam",
    "elevation": "300 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Congo",
    "capital": "Brazzaville",
    "population": 6484437,
    "gdp": "79.12 billion (USD)",
    "area": "2,344,858 km2",
    "coordinates": "4.0383 S 21.7587 E",
    "official_languages": "French",
    "currency": "Congolese Franc (CDF)",
    "country_code": "+242",
    "religion": "Christianity",
    "elevation": "726 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Costa Rica",
    "capital": "San Jose",
    "population": 5152950,
    "gdp": "95.37 billion (USD)",
    "area": "51,100 km2",
    "coordinates": "9.7489 N 83.7534 W",
    "official_languages": "Spanish",
    "currency": "Costa Rican Colon (CRC)",
    "country_code": "+506",
    "religion": "Christianity",
    "elevation": "746 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Croatia",
    "capital": "Zagreb",
    "population": 3848160,
    "gdp": "92.53 billion (USD)",
    "area": "56,594 km2",
    "coordinates": "45.1000 N 15.2000 E",
    "official_languages": "Croatian",
    "currency": "Euro(EUR)",
    "country_code": "+385",
    "religion": "Christianity",
    "elevation": "331 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Cuba",
    "capital": "Havana",
    "population": 11152631,
    "gdp": "107.35 billion (USD)",
    "area": "110,860 km2",
    "coordinates": "21.5218 N, 77.7812 W",
    "official_languages": "Spanish",
    "currency": "Cuban Peso (CUP)",
    "country_code": "+53",
    "religion": "Christianity",
    "elevation": "108 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Cyprus",
    "capital": "Nicosia",
    "population": 1370754,
    "gdp": "36.33 billion (USD)",
    "area": "9,251 km2",
    "coordinates": "35.1264 N, 33.4299 E",
    "official_languages": "Greek,Turkis,English",
    "currency": "Euro(EUR)",
    "country_code": "+357",
    "religion": "Christianity",
    "elevation": "91 m",
    "gold_reserves": "13.90 Tonnes"
  },
  {
    "country": "Czechia",
    "capital": "Prague",
    "population": 10609239,
    "gdp": "345.04 billion (USD)",
    "area": "78,871 km2",
    "coordinates": "49.8175 N 15.4730 E",
    "official_languages": "Czech,Slovak",
    "currency": "Ceska Koruna (CZK)",
    "country_code": "+420",
    "religion": "Christianity",
    "elevation": "430 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Denmark",
    "capital": "Copenhagen",
    "population": 5992095,
    "gdp": "429.46 billion (USD)",
    "area": "43,094 km2",
    "coordinates": "56.2639 N, 95018 E",
    "official_languages": "Danish",
    "currency": "Danish Kroner (DKK)",
    "country_code": "+45",
    "religion": "Christianity",
    "elevation": "34 m",
    "gold_reserves": "66.55 Tonnes"
  },
  {
    "country": "Djibouti",
    "capital": "Djibouti City",
    "population": 1120000,
    "gdp": "4.09 billion (USD)",
    "area": "23,200 km2",
    "coordinates": "11.8251 N, 42.5903 E",
    "official_languages": "French, Arabic",
    "currency": "Djiboutian franc (DJF)",
    "country_code": "+253",
    "religion": "Islam",
    "elevation": "2,063 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Dominica",
    "capital": "Roseau",
    "population": 73685,
    "gdp": "697 million (USD)",
    "area": "750km2",
    "coordinates": "15.4150 N, 61.3710 W",
    "official_languages": "English",
    "currency": "East Caribbean Dollar (XCD)",
    "country_code": "+1-767",
    "religion": "Christianity",
    "elevation": "724 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Dominican Republic",
    "capital": "Santo Domingo",
    "population": 11230000,
    "gdp": "124.28 billion (USD)",
    "area": "48,670 km2",
    "coordinates": "18.7357 N, 70.1627 W",
    "official_languages": "Spanish",
    "currency": "Dominican Peso (DOP)",
    "country_code": "+1-809",
    "religion": "Christianity",
    "elevation": "424 m",
    "gold_reserves": "0.57 Tonnes"
  },
  {
    "country": "DPRK",
    "capital": "Pyongyang",
    "population": 26319924,
    "gdp": "28.5 billion (USD)",
    "area": "120,540 km2",
    "coordinates": "40.3399 N 127.5101 E",
    "official_languages": "Korean",
    "currency": "North Korean Won (KPW)",
    "country_code": "+850",
    "religion": "Shamanism,Chondoism",
    "elevation": "",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "DRC",
    "capital": "Kinshasa",
    "population": 112832473,
    "gdp": "66.38 billion (USD)",
    "area": "2,344,858 km2",
    "coordinates": "4.0383 S, 21.7587 E",
    "official_languages": "French",
    "currency": "Congolese Franc (FC)",
    "country_code": "+243",
    "religion": "Christianity",
    "elevation": "",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Ecuador",
    "capital": "Quito",
    "population": 18563370,
    "gdp": "124.68 billion (USD)",
    "area": "283,561 km2",
    "coordinates": "1.8312 S, 78.1834 W",
    "official_languages": "Spanish",
    "currency": "United States Dollar (USD)",
    "country_code": "+593",
    "religion": "Christianity",
    "elevation": "1,117 m",
    "gold_reserves": "26.28 Tonnes"
  },
  {
    "country": "Egypt",
    "capital": "Cairo",
    "population": 118365995,
    "gdp": "389.06 billion (USD)",
    "area": "1,002,450 km2",
    "coordinates": "26.8206 N, 30.8025 E",
    "official_languages": "Arabic",
    "currency": "Egyptian Pound (EGP)",
    "country_code": "+20",
    "religion": "Islam",
    "elevation": "321 m",
    "gold_reserves": "126.82 Tonnes"
  },
  {
    "country": "El Salvador",
    "capital": "San Salvador",
    "population": 6365503,
    "gdp": "35.36 billion (USD)",
    "area": "21,041 km2",
    "coordinates": "13.7942 N, 88.8965 W",
    "official_languages": "Spanish",
    "currency": "United States Dollar (USD), Bitcoin",
    "country_code": "+503",
    "religion": "Christianity",
    "elevation": "442 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Equatorial Guinea",
    "capital": "Malabo",
    "population": 1670000,
    "gdp": "12.77 billion (USD)",
    "area": "28,051 km2",
    "coordinates": "1.6508 N, 10.2679E",
    "official_languages": "Spanish, Portuguese, French",
    "currency": "Central African CFA franc (CFA)",
    "country_code": "+240",
    "religion": "Christianity",
    "elevation": "577 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Eritrea",
    "capital": "Asmara",
    "population": 3889630,
    "gdp": "2.0 billion (USD)",
    "area": "121,630 km2",
    "coordinates": "15.1794 N, 39.7823 E",
    "official_languages": "Tigrinya, Tigre, Saho, Kunama, Rashaida, Bilen, Afar, Beni, Amir, and Nera.",
    "currency": "Eritrean Nakfa (ERN)",
    "country_code": "+291",
    "religion": "Christianity/Islam",
    "elevation": "853 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Estonia",
    "capital": "Tallinn",
    "population": 1350833,
    "gdp": "42.76 billion (USD)",
    "area": "45,335 km2",
    "coordinates": "58.5953 N, 25.0136 E",
    "official_languages": "Estonian",
    "currency": "Euro (EUR)",
    "country_code": "+372",
    "religion": "Christianity",
    "elevation": "61 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Eswatini",
    "capital": "Mbabane",
    "population": 1200000,
    "gdp": "44.89 billion(USD)",
    "area": "1 7,364 km2",
    "coordinates": "26.5225 S, 31.4659 E",
    "official_languages": "Swati,English",
    "currency": "Swazi Lilangeni (SZL)",
    "country_code": "+268",
    "religion": "Christianity",
    "elevation": "305 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Ethiopia",
    "capital": "Addis Ababa",
    "population": 135472051,
    "gdp": "163.7 billion (USD)",
    "area": "1,104,300 km2",
    "coordinates": "9.1450 N, 40.4897 E",
    "official_languages": "Afar, Amharic, Oromo",
    "currency": "Ethiopian Birr(ETB)",
    "country_code": "+251",
    "religion": "Christianity",
    "elevation": "1,330 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Fiji",
    "capital": "Suva",
    "population": 933154,
    "gdp": "5,842 million (USD)",
    "area": "18,274 km2",
    "coordinates": "17.7134 S, 178.0650 E",
    "official_languages": "English, Fijian, Fiji Hindi",
    "currency": "Fijian Dollar (FJD)",
    "country_code": "+679",
    "religion": "Christianity",
    "elevation": "662 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Finland",
    "capital": "Helsinki",
    "population": 5623329,
    "gdp": "299.83 billion (USD)",
    "area": "338,145 km2",
    "coordinates": "61.9241 N, 25.7482 E",
    "official_languages": "Finnish, Swedish",
    "currency": "Euro (EUR)",
    "country_code": "+358",
    "religion": "Christianity",
    "elevation": "164 m",
    "gold_reserves": "49.02 Tonnes"
  },
  {
    "country": "France",
    "capital": "Paris",
    "population": 66650804,
    "gdp": "842 billion(USD)",
    "area": "551,695 km2",
    "coordinates": "46.2276 N, 2.2137 E",
    "official_languages": "French",
    "currency": "Euro (EUR)",
    "country_code": "+33",
    "religion": "Christianity",
    "elevation": "375 m",
    "gold_reserves": "2,437t"
  },
  {
    "country": "Gabon",
    "capital": "Libreville",
    "population": 2593130,
    "gdp": "21.3 billion (USD)",
    "area": "267,667 km2",
    "coordinates": "0.8037 S, 11.6094 E",
    "official_languages": "French",
    "currency": "Central African CFA franc (XAF)",
    "country_code": "+241",
    "religion": "Christianity",
    "elevation": "377 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Gambia",
    "capital": "Banjui",
    "population": 2911207,
    "gdp": "2.51 billion (USD)",
    "area": "11,300 km2",
    "coordinates": "13.4432 N, 15.3101 W",
    "official_languages": "English",
    "currency": "Gambian Dalasi (GMD)",
    "country_code": "+220",
    "religion": "Islam",
    "elevation": "34 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Georgia",
    "capital": "Tbilisi",
    "population": 3806671,
    "gdp": "33.78 billion (USD)",
    "area": "69,700 km2",
    "coordinates": "42.3154 N, 43.3569 E",
    "official_languages": "Georgian",
    "currency": "Georgian Lari (GEL)",
    "country_code": "+995",
    "religion": "Christianity",
    "elevation": "1,432 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Germany",
    "capital": "Berlin",
    "population": 84075075,
    "gdp": "4,659.93 billion (USD)",
    "area": "357,600 km2",
    "coordinates": "51.1657 N, 10.4515 E",
    "official_languages": "German",
    "currency": "Euro (EUR)",
    "country_code": "+49",
    "religion": "Christianity",
    "elevation": "263 m",
    "gold_reserves": "3,351.53 Tonnes"
  },
  {
    "country": "Ghana",
    "capital": "Accra",
    "population": 35064272,
    "gdp": "135.1 billion (USD)",
    "area": "239,567 km2",
    "coordinates": "7.9465 N 1.0232 W",
    "official_languages": "English",
    "currency": "Ghanaian Cedi (GHS)",
    "country_code": "+233",
    "religion": "Christianity",
    "elevation": "190 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Greece",
    "capital": "Athens",
    "population": 9938844,
    "gdp": "257.07 billion (USD)",
    "area": "131,957 km2",
    "coordinates": "39.0742 N, 21.8243 E",
    "official_languages": "Greek",
    "currency": "Euro (EUR)",
    "country_code": "+30",
    "religion": "Christianity",
    "elevation": "498 m",
    "gold_reserves": "114.52 Tonnes"
  },
  {
    "country": "Grenada",
    "capital": "Saint George's",
    "population": 117303,
    "gdp": "1.39 billion (USD)",
    "area": "344.5 km2",
    "coordinates": "12.1165 N, 61.6790 W",
    "official_languages": "English",
    "currency": "East Caribran Dollar (XCD)",
    "country_code": "+1-473",
    "religion": "Christianity",
    "elevation": "420 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Guatemala",
    "capital": "Guatemala city",
    "population": 18687881,
    "gdp": "113.20 billion (USD)",
    "area": "108,889 km2",
    "coordinates": "15.7835 N, 90.2308 W",
    "official_languages": "Spanish",
    "currency": "Guatemalan Quetzal (GTQ)",
    "country_code": "+502",
    "religion": "Christianity",
    "elevation": "759 m",
    "gold_reserves": "6.89 Tonnes"
  },
  {
    "country": "Guinea",
    "capital": "Conakry",
    "population": 15099727,
    "gdp": "25.33 billion (USD)",
    "area": "245,857 km2",
    "coordinates": "9.9456 N, 9.6966 W",
    "official_languages": "French",
    "currency": "Guinea franc (GNF)",
    "country_code": "+224",
    "religion": "Islam",
    "elevation": "472 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Guinea-Bissau",
    "capital": "Bissau",
    "population": 2110000,
    "gdp": "2.12 billion (USD)",
    "area": "36,125 km2",
    "coordinates": "11.8037 N, 15.1804 W",
    "official_languages": "Portuguese",
    "currency": "West African CFA franc (XOF)",
    "country_code": "+245",
    "religion": "Islam",
    "elevation": "277 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Guyana",
    "capital": "Georgetown",
    "population": 835986,
    "gdp": "24.84 billion (USD)",
    "area": "214,969 km2",
    "coordinates": "4.8604 N, 58.9302 W",
    "official_languages": "English",
    "currency": "Guyanese Dollar (GYD)",
    "country_code": "+592",
    "religion": "Christianity",
    "elevation": "207 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Holy See",
    "capital": "Vatican City",
    "population": 533,
    "gdp": "",
    "area": ".44km2",
    "coordinates": "41.9029 N, 12.4534 E",
    "official_languages": "Latin,Italian",
    "currency": "Euro (EUR)",
    "country_code": "+39",
    "religion": "Christianity",
    "elevation": "47 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Haiti",
    "capital": "Port-au-Prince",
    "population": 11906095,
    "gdp": "26.23 billion (USD)",
    "area": "27,750 km2",
    "coordinates": "18.9712 N, 72.2852 W",
    "official_languages": "Haitian Creole,French",
    "currency": "Haitian Gourde (HTG)",
    "country_code": "+509",
    "religion": "Christianity",
    "elevation": "470 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Honduras",
    "capital": "Tegucigalpa",
    "population": 11005850,
    "gdp": "37.09 billion (USD)",
    "area": "112,492 km2",
    "coordinates": "15.2000 N, 86.2419 W",
    "official_languages": "Spanish",
    "currency": "Honduran Lempira (HNL)",
    "country_code": "+504",
    "religion": "Christianity",
    "elevation": "684 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Hungary",
    "capital": "Budapest",
    "population": 9632287,
    "gdp": "222.90 billion (USD)",
    "area": "93,030 km2",
    "coordinates": "47.1625 N, 19.5033 E",
    "official_languages": "Hungarian",
    "currency": "Hungarian Forint (HUF)",
    "country_code": "+36",
    "religion": "Christianity",
    "elevation": "143 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Iceland",
    "capital": "Reykjavik",
    "population": 398266,
    "gdp": "34.26 billion (USD)",
    "area": "103,125 km2",
    "coordinates": "64.9631 N, 19.0208 W",
    "official_languages": "Icelandic",
    "currency": "Icelandic Krona (ISK)",
    "country_code": "+354",
    "religion": "Christianity",
    "elevation": "557 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "India",
    "capital": "New Delhi",
    "population": 1463865525,
    "gdp": "4.19 trillion (USD)",
    "area": "3,287,263 km2",
    "coordinates": "20.5937 N, 78.9629 E",
    "official_languages": "Hindi, English",
    "currency": "Indian Rupee (INR)",
    "country_code": "+91",
    "religion": "Hindu",
    "elevation": "621 m",
    "gold_reserves": "853.63 Tonnes"
  },
  {
    "country": "Indonesia",
    "capital": "Jakarta",
    "population": 285721236,
    "gdp": "1.396 trillion (USD)",
    "area": "1,904,569 km2",
    "coordinates": "0.7893 S, 113.9213 E",
    "official_languages": "Indonesian",
    "currency": "Indonesian Rupiah (IDR)",
    "country_code": "+62",
    "religion": "Islam",
    "elevation": "367 m",
    "gold_reserves": "78.57 Tonnes"
  },
  {
    "country": "Iran",
    "capital": "Tehran",
    "population": 92417681,
    "gdp": "436.91 billion (USD)",
    "area": "1,648,195 km2",
    "coordinates": "32.4279 N, 53.6880 E",
    "official_languages": "Persian(Farsi)",
    "currency": "Iranian Rial (IRR)",
    "country_code": "+98",
    "religion": "Islam",
    "elevation": "1,305 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Iraq",
    "capital": "Baghdad",
    "population": 46615172,
    "gdp": "270.87 billion (USD)",
    "area": "437,072 km2",
    "coordinates": "33.2232 N, 43.6793 E",
    "official_languages": "Arabic, Kurdish",
    "currency": "Iraqi Dinar (IQD)",
    "country_code": "+964",
    "religion": "Islam",
    "elevation": "312 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Ireland",
    "capital": "Dublin",
    "population": 5308039,
    "gdp": "690 billion (USD)",
    "area": "84,421 km2",
    "coordinates": "53.1424 N, 7.6921 W",
    "official_languages": "Irish, English",
    "currency": "Euro (EUR)",
    "country_code": "+353",
    "religion": "Christianity",
    "elevation": "118 m",
    "gold_reserves": "12.04 Tonnes"
  },
  {
    "country": "Israel",
    "capital": "Jerusalem",
    "population": 9517181,
    "gdp": "540.38 billion (USD)",
    "area": "22,072 km2",
    "coordinates": "31.0461 N, 34.8516E",
    "official_languages": "Hebrew, Arabic",
    "currency": "Isreali New Shekel (ILS)",
    "country_code": "+972",
    "religion": "Jewish",
    "elevation": "508 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Italy",
    "capital": "Rome",
    "population": 59146260,
    "gdp": "2.373 trillion (USD)",
    "area": "301,230 km2",
    "coordinates": "41.8719 N, 12.5674 E",
    "official_languages": "Italian",
    "currency": "Euro EUR)",
    "country_code": "+39",
    "religion": "Christianity",
    "elevation": "538 m",
    "gold_reserves": "2,451.84 Tonnes"
  },
  {
    "country": "Jamaica",
    "capital": "Kingston",
    "population": 2837077,
    "gdp": "20.07 billion (USD)",
    "area": "10,990 km2",
    "coordinates": "18.1096 N, 77.2975 W",
    "official_languages": "English",
    "currency": "Jamaican Dollar (JMD)",
    "country_code": "+1-876",
    "religion": "Christianity",
    "elevation": "340 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Japan",
    "capital": "Tokyo",
    "population": 123103479,
    "gdp": "4.03 trillion (USD)",
    "area": "377,975 km2",
    "coordinates": "36.2048 N, 138.2529 E",
    "official_languages": "Japanese",
    "currency": "Japanese Yen (JPY)",
    "country_code": "+81",
    "religion": "Shinto, Buddhism",
    "elevation": "438 m",
    "gold_reserves": "846 Tonnes"
  },
  {
    "country": "Jordan",
    "capital": "Amman",
    "population": 11520684,
    "gdp": "53.43 billion (USD)",
    "area": "89,342 km2",
    "coordinates": "30.5852 N, 36.2384 E",
    "official_languages": "Arabic",
    "currency": "Jordanian Dinar (JOD)",
    "country_code": "+962",
    "religion": "Islam",
    "elevation": "812 m",
    "gold_reserves": "68.78 Tones"
  },
  {
    "country": "Kazakhstan",
    "capital": "Astana",
    "population": 19620000,
    "gdp": "288.41 billion (USD)",
    "area": "2,700,000 km2",
    "coordinates": "48.0196 N, 66.9237 E",
    "official_languages": "Kazakh, Russian",
    "currency": "Kazakhstani Tenge (KZT)",
    "country_code": "+7",
    "religion": "Islam",
    "elevation": "387 m",
    "gold_reserves": "285.94 Tonnes"
  },
  {
    "country": "Kenya",
    "capital": "Nairobi",
    "population": 57532493,
    "gdp": "124.5 billion (USD)",
    "area": "580,367 km2",
    "coordinates": "0.0236 S, 37.9062 E",
    "official_languages": "English, Swahili",
    "currency": "Kenyan Shilling (KES)",
    "country_code": "+254",
    "religion": "Christianity",
    "elevation": "762 m",
    "gold_reserves": "0.02 Tonnes"
  },
  {
    "country": "Kiribati",
    "capital": "Kuwait City",
    "population": 5026078,
    "gdp": "310 billion (USD)",
    "area": "811 km2",
    "coordinates": "1.4421 N, 172.9830 E",
    "official_languages": "Kiribati, English",
    "currency": "Kiribati Dollar, Australian Dollar",
    "country_code": "+686",
    "religion": "Christianity",
    "elevation": "2 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Kyrgyzstan",
    "capital": "Bishkek",
    "population": 6800000,
    "gdp": "17.49 billion (USD)",
    "area": "200,105 km2",
    "coordinates": "41.2044 N, 74.7661 E",
    "official_languages": "Kyrgyz, Russian",
    "currency": "Kyrgystani Som (KGS)",
    "country_code": "+996",
    "religion": "Islam",
    "elevation": "2,750 m",
    "gold_reserves": "25.96 Tonnes"
  },
  {
    "country": "Kuwait",
    "capital": "Kuwait City",
    "population": 5026078,
    "gdp": "163.7 billion (USD)",
    "area": "17,818 km2",
    "coordinates": "29.3117 N, 47.4818 E",
    "official_languages": "Arabic",
    "currency": "Kuwait DInar (KWD)",
    "country_code": "+965",
    "religion": "Islam",
    "elevation": "108 m",
    "gold_reserves": "78.97 Tonnes"
  },
  {
    "country": "Lao People's Democratic Republic",
    "capital": "Vientiane",
    "population": 7873046,
    "gdp": "16.50 billion (USD)",
    "area": "236,800 km2",
    "coordinates": "19.8563 N, 102.4955 E",
    "official_languages": "Leo",
    "currency": "Laotian Kip (LAK)",
    "country_code": "+856",
    "religion": "Buddhist",
    "elevation": "710 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Latvia",
    "capital": "Riga",
    "population": 1853559,
    "gdp": "43.52 billion (USD)",
    "area": "64,589 km2",
    "coordinates": "56.8796 N, 24.6032 E",
    "official_languages": "Latvian",
    "currency": "Euro (EUR)",
    "country_code": "+371",
    "religion": "Christianity",
    "elevation": "87 m",
    "gold_reserves": "6.66 Tonnes"
  },
  {
    "country": "Lebanon",
    "capital": "Beirut",
    "population": 5849421,
    "gdp": "28 billion (USD)",
    "area": "10,452 km2",
    "coordinates": "33.8547 N, 35.8623 E",
    "official_languages": "Arabic",
    "currency": "Lebanese Pound (LBP)",
    "country_code": "+961",
    "religion": "Islam/Christianity",
    "elevation": "1,250 m",
    "gold_reserves": "287 Tonnes"
  },
  {
    "country": "Lesotho",
    "capital": "Maseru",
    "population": 2310000,
    "gdp": "2.27 billion (USD)",
    "area": "30,355 km2",
    "coordinates": "29.6100 S, 28.2336 E",
    "official_languages": "Southern Sotho, English",
    "currency": "Lesotho Loti (LSL)",
    "country_code": "+266",
    "religion": "Christianity",
    "elevation": "634 m",
    "gold_reserves": "Low/Negligible"
  },
  {
    "country": "Liberia",
    "capital": "Monrovia",
    "population": 5731206,
    "gdp": "4.75 billion (USD)",
    "area": "111,369 km2",
    "coordinates": "6.4281 N, 9.4295 W",
    "official_languages": "English",
    "currency": "Liberian Dollar (LRD)",
    "country_code": "+231",
    "religion": "Christianity",
    "elevation": "243 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Libya",
    "capital": "Tripoli",
    "population": 7458555,
    "gdp": "46.64 billion (USD)",
    "area": "1,759,540 km2",
    "coordinates": "26.3351 N, 17.2283 E",
    "official_languages": "Arabic",
    "currency": "Libyan Dinar (LYD)",
    "country_code": "+218",
    "religion": "Islam",
    "elevation": "423 m",
    "gold_reserves": "146.65nTonnes"
  },
  {
    "country": "Liechtenstein",
    "capital": "Vaduz",
    "population": 40050,
    "gdp": "8.29 billion (USD)",
    "area": "160 km2",
    "coordinates": "47.1410 N, 9.5209 E",
    "official_languages": "German",
    "currency": "Swiss Franc (CHF)",
    "country_code": "+423",
    "religion": "Christianity",
    "elevation": "2,774 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Lithuania",
    "capital": "Vilnius",
    "population": 2830144,
    "gdp": "84.87 billion (USD)",
    "area": "65,300 km2",
    "coordinates": "55.1694 N, 23.8813 E",
    "official_languages": "Lithuanian",
    "currency": "Euro (EUR)",
    "country_code": "+370",
    "religion": "Christianity",
    "elevation": "110 m",
    "gold_reserves": "5.82 Tonnes"
  },
  {
    "country": "Luxembourg",
    "capital": "Luxembourg",
    "population": 680453,
    "gdp": "93.20 billion (USD)",
    "area": "2,586 km2",
    "coordinates": "49.8153 N, 6.1296 E",
    "official_languages": "Luxembourgish, French, German",
    "currency": "Euro (EUR)",
    "country_code": "+352",
    "religion": "Christianity",
    "elevation": "325 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Madagascar",
    "capital": "Antananarivo",
    "population": 32740678,
    "gdp": "17.42 billion (USD)",
    "area": "587,041 km2",
    "coordinates": "18.7669 S, 46.8691 E",
    "official_languages": "Malagasy, French",
    "currency": "Malagasy Ariary (MGA)",
    "country_code": "+261",
    "religion": "Christianity",
    "elevation": "615 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Malawi",
    "capital": "Lilongwe",
    "population": 22216120,
    "gdp": "11.01 billion (USD)",
    "area": "118,484 km2",
    "coordinates": "13.2543 S, 34.3015 E",
    "official_languages": "English",
    "currency": "Malawian Kwacha (MWK)",
    "country_code": "+265",
    "religion": "Christianity",
    "elevation": "779 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Malaysia",
    "capital": "Kuala Lumpur",
    "population": 35977838,
    "gdp": " 421.97 billion (USD)",
    "area": "330,803 km2",
    "coordinates": "4.2105 N, 101.9758 E",
    "official_languages": "Malay",
    "currency": "Malaysian Ringgit (MYR)",
    "country_code": "+60",
    "religion": "Islam",
    "elevation": "419 m",
    "gold_reserves": "38.88 Tonnes"
  },
  {
    "country": "Maldives",
    "capital": "Male",
    "population": 529676,
    "gdp": "6.98 billion (USD)",
    "area": "298 km2",
    "coordinates": "3.2028 N, 73.2207 E",
    "official_languages": "Dhivehi",
    "currency": "Maldivian Rufiyaa (MVR)",
    "country_code": "+960",
    "religion": "Islam",
    "elevation": "1.5 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Mali",
    "capital": "Bamako",
    "population": 22590000,
    "gdp": "26.59 billion (USD)",
    "area": "1,240,192 km2",
    "coordinates": "17.5707 N, 3.9962 W",
    "official_languages": "Soninke, Tamasheq",
    "currency": "West African CFA franc (XOF)",
    "country_code": "+223",
    "religion": "Islam",
    "elevation": "343 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Malta",
    "capital": "Valletta",
    "population": 545405,
    "gdp": "24.32 billion (USD)",
    "area": "316 km2",
    "coordinates": "35.9375 N, 14.3754 E",
    "official_languages": "Maltese, English",
    "currency": "Euro (EUR)",
    "country_code": "+356",
    "religion": "Christianity",
    "elevation": "127 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Marshall Islands",
    "capital": "Majuro",
    "population": 36786,
    "gdp": "0.28 billion (USD)",
    "area": "181 km2",
    "coordinates": "7.1315 N, 171.1845 E",
    "official_languages": "Marshallese, English",
    "currency": "United States Dollar (USD)",
    "country_code": "+692",
    "religion": "Christianity",
    "elevation": "2m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Mauritania",
    "capital": "Nouakchott",
    "population": 4740000,
    "gdp": "10.77 billion (USD)",
    "area": "1,030,700 km2",
    "coordinates": "21.0079 N, 10.9408 W",
    "official_languages": "Arabic",
    "currency": "Mauritanian Ouguiya (MRU)",
    "country_code": "+222",
    "religion": "Islam",
    "elevation": "276 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Mauritius",
    "capital": "Port Luis",
    "population": 1260000,
    "gdp": "14.95 billion (USD)",
    "area": "2,040 km2",
    "coordinates": "20.3484 S, 57.5522 E",
    "official_languages": "English",
    "currency": "Maurituan Rupee (MUR)",
    "country_code": "+230",
    "religion": "Hinduism",
    "elevation": "828 m",
    "gold_reserves": "12.42 Tonnes"
  },
  {
    "country": "Mexico",
    "capital": "Mexico City",
    "population": 131946900,
    "gdp": "1,852.72 billion (USD)",
    "area": "1,972,550 km2",
    "coordinates": "23.6345 N, 102.5528 W",
    "official_languages": "Spanish",
    "currency": "Mexican Peso (MXN)",
    "country_code": "+52",
    "religion": "Christianity",
    "elevation": "1,111 m",
    "gold_reserves": "120.37 Tonnes"
  },
  {
    "country": "Micronesia",
    "capital": "Palikir",
    "population": 527962,
    "gdp": "470 million (USD)",
    "area": "702 km2",
    "coordinates": "7.4256 N, 150.5508 E",
    "official_languages": "English",
    "currency": "United States Dollar (USD)",
    "country_code": "+691",
    "religion": "Christianity",
    "elevation": "396 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Moldova",
    "capital": "Chisinau",
    "population": 2996106,
    "gdp": "18.20 billion (USD)",
    "area": "33,483 km2",
    "coordinates": "47.4116 N, 28.3699 E",
    "official_languages": "Romanian",
    "currency": "Moldovan Leu (MDL)",
    "country_code": "+373",
    "religion": "Christianity",
    "elevation": "147 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Monaco",
    "capital": "Monaco",
    "population": 38459,
    "gdp": "10 billion (USD)",
    "area": "2.08 km2",
    "coordinates": "43.7384 N, 7.4246 E",
    "official_languages": "French",
    "currency": "Euro(EUR)",
    "country_code": "+377",
    "religion": "Christianity",
    "elevation": "81 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Mongolia",
    "capital": "Ulaanbaatar",
    "population": 3537947,
    "gdp": "23.59 billion (USD)",
    "area": "1,564,116 km2",
    "coordinates": "46.8625 N, 103.8467 E",
    "official_languages": "Mongolian",
    "currency": "Mongolian Tugrik (MNT)",
    "country_code": "+976",
    "religion": "Buddhism",
    "elevation": "1,580 m",
    "gold_reserves": "3.88 Tonnes"
  },
  {
    "country": "Montenegro",
    "capital": "Podgorica",
    "population": 632729,
    "gdp": "8.07 billion (USD)",
    "area": "13,812 km2",
    "coordinates": "42.7087 N, 19.3744 E",
    "official_languages": "Montenegrin",
    "currency": "Euro (EUR)",
    "country_code": "+382",
    "religion": "Christianity",
    "elevation": "1,086 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Morocco",
    "capital": "Rabat",
    "population": 38430770,
    "gdp": "154.43 billion (USD)",
    "area": "446,550 km2",
    "coordinates": "31.7917 N, 7.0926 W",
    "official_languages": "Arabic, Moroccan Berber",
    "currency": "Moroccan Dirham (MAD)",
    "country_code": "+212",
    "religion": "Islam",
    "elevation": "800m",
    "gold_reserves": "22.12 Tonnes"
  },
  {
    "country": "Mozambique",
    "capital": "Maputo",
    "population": 35212421,
    "gdp": "22.42 billion (USD)",
    "area": "801,537 km2",
    "coordinates": "18.6657 S, 35.5296 E",
    "official_languages": "Portuguese",
    "currency": "Mozambican Metical (MZN)",
    "country_code": "+258",
    "religion": "Christianity",
    "elevation": "345 m",
    "gold_reserves": "3.94 Tonnes"
  },
  {
    "country": "Myanmar",
    "capital": "Naypyidaw",
    "population": 54850648,
    "gdp": "74.08 billion (USD)",
    "area": "676,575 km2",
    "coordinates": "21.9162 N, 95.9560 E",
    "official_languages": "Burmese",
    "currency": "Myanmar Kyat (MMK)",
    "country_code": "+95",
    "religion": "Buddhism",
    "elevation": "702 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Namibia",
    "capital": "Windhoek",
    "population": 3092816,
    "gdp": "13.37 billion (USD)",
    "area": "824,292 km2",
    "coordinates": "22.9576 S 18.4904 E",
    "official_languages": "English",
    "currency": "Namibian Dollar (NAD)",
    "country_code": "+264",
    "religion": "Christianity",
    "elevation": "1,141 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Nauru",
    "capital": "Yaren",
    "population": 11993,
    "gdp": "160 million (USD)",
    "area": "21 km2",
    "coordinates": "0.5228 S, 166.9315 E",
    "official_languages": "Nauruan, English",
    "currency": "Australian Dollar (AUD)",
    "country_code": "+674",
    "religion": "Christianity",
    "elevation": "70 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Nepal",
    "capital": "Kathmandu",
    "population": 29618118,
    "gdp": "42.91 billion (USD)",
    "area": "147,181 km2",
    "coordinates": "28.3949 N, 84.1240 E",
    "official_languages": "Nepali",
    "currency": "Nepalese Rupee (NPR)",
    "country_code": "+977",
    "religion": "Hindu",
    "elevation": "3,265 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Netherlands",
    "capital": "Amsterdam",
    "population": 18346819,
    "gdp": "1,227.54 billion (USD)",
    "area": "41,850 km2",
    "coordinates": "52.1326 N, 5.2913 E",
    "official_languages": "Dutch",
    "currency": "Euro (EUR)",
    "country_code": "+31",
    "religion": "Christianity",
    "elevation": "30 m",
    "gold_reserves": "612.45 Tonnes"
  },
  {
    "country": "New Zealand",
    "capital": "Wellington",
    "population": 5251899,
    "gdp": "260.24 billion (USD)",
    "area": "267,710 km2",
    "coordinates": "40.9006 S, 174.8860 E",
    "official_languages": "Maori",
    "currency": "New Zealand Dollar (NZD)",
    "country_code": "+64",
    "religion": "Christianity",
    "elevation": "388 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Nicaragua",
    "capital": "Managua",
    "population": 7007502,
    "gdp": "19.71 billion (USD)",
    "area": "130,370 km2",
    "coordinates": "12.8654 N, 85.2072 W",
    "official_languages": "Spanish",
    "currency": "Nicaraguan Cordoba (NIO)",
    "country_code": "+505",
    "religion": "Christianity",
    "elevation": "298 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Niger",
    "capital": "Niamey",
    "population": 27917831,
    "gdp": "19.54 billion (USD)",
    "area": "1,267,000 km2",
    "coordinates": "17.6078 N, 8.0817 E",
    "official_languages": "French",
    "currency": "West African CFA franc (XOF)",
    "country_code": "+227",
    "religion": "Islam",
    "elevation": "2,022 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Nigeria",
    "capital": "Abuja",
    "population": 237527782,
    "gdp": "187.76 billion (USD)",
    "area": "923,768 km2",
    "coordinates": "9.0820 N, 8.6753 E",
    "official_languages": "English",
    "currency": "Nigerian Naira (NGN)",
    "country_code": "+234",
    "religion": "Christianity",
    "elevation": "380 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "North Macedonia",
    "capital": "Skopje",
    "population": 1813791,
    "gdp": "16.69 billion (USD)",
    "area": "25,436 km2",
    "coordinates": "41.6086 N, 21.7453 E",
    "official_languages": "Macedonian, Albanian",
    "currency": "Macedonian Denar (MKD)",
    "country_code": "+389",
    "religion": "Christianity",
    "elevation": "741 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Norway",
    "capital": "Oslo",
    "population": 5623071,
    "gdp": "483.73 billion (USD)",
    "area": "385,199 km2",
    "coordinates": "60.4720 N, 8.4689 E",
    "official_languages": "Norwegian",
    "currency": "Norwegian Krone (NOK)",
    "country_code": "+47",
    "religion": "Christianity",
    "elevation": "460 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Oman",
    "capital": "Muscat",
    "population": 5494691,
    "gdp": "106.94 billion (USD)",
    "area": "309,500 km2",
    "coordinates": "21.4735 N, 55.9754 E",
    "official_languages": "Arabic",
    "currency": "Omani Rial (OMR)",
    "country_code": "+968",
    "religion": "Islam",
    "elevation": "310 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Pakistan",
    "capital": "Islamabad",
    "population": 251269164,
    "gdp": "373.08 billion (USD) ",
    "area": "881,913 km2",
    "coordinates": "30.3753 N, 69.3451 E",
    "official_languages": "Urdu, English",
    "currency": "Pakistani Rupee (PKR)",
    "country_code": "+92",
    "religion": "Islam",
    "elevation": "900 m",
    "gold_reserves": "64.72 Tonnes"
  },
  {
    "country": "Palau",
    "capital": "Ngerulmud",
    "population": 18060,
    "gdp": "0.28 billion (USD)",
    "area": "459 km2",
    "coordinates": "7.5150 N, 134.5825 E",
    "official_languages": "Palauan, English",
    "currency": "United States Dollar (USD)",
    "country_code": "+680",
    "religion": "Christianity",
    "elevation": "242 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Panama",
    "capital": "Panama City",
    "population": 4458760,
    "gdp": "86.26 billion (USD)",
    "area": "75,417 km2",
    "coordinates": "8.5380 N, 80.7821 W",
    "official_languages": "Spanish",
    "currency": "Panamanian Balboa (PAB)",
    "country_code": "+507",
    "religion": "Christianity",
    "elevation": "360 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Papua New Guinea",
    "capital": "Port Moresby",
    "population": 10389640,
    "gdp": "32.54 billion (USD)",
    "area": "462,840 km2",
    "coordinates": "6.3150 S, 143.9555 E",
    "official_languages": "Tok Pisin, English",
    "currency": "Papua New Guinean Kina (PGK)",
    "country_code": "+675",
    "religion": "Christianity",
    "elevation": "667 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Paraguay",
    "capital": "Asuncion",
    "population": 6844150,
    "gdp": "44.46 billion (USD)",
    "area": "406,752 km2",
    "coordinates": "23.4425 S, 58.4438 W",
    "official_languages": "Spanish, Paraguayan, guarani",
    "currency": "Paraguayan Guarani (PYG)",
    "country_code": "+595",
    "religion": "Christianity",
    "elevation": "178 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Peru",
    "capital": "Lima",
    "population": 33845620,
    "gdp": "289.22 billion (USD)",
    "area": "1,285,220 km2",
    "coordinates": "9.1900 S, 75.0152 W",
    "official_languages": "Spanish",
    "currency": "Peruvian Sol (PEN)",
    "country_code": "+51",
    "religion": "Christianity",
    "elevation": "1,555 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Philippines",
    "capital": "Manila",
    "population": 114370000,
    "gdp": "461.62 billion (USD)",
    "area": "300,000 km2",
    "coordinates": "12.8797 N, 121.7740 E",
    "official_languages": "Filipino, English",
    "currency": "Philippine Peso (PHP)",
    "country_code": "+63",
    "religion": "Christianity",
    "elevation": "442 m",
    "gold_reserves": "128.12 Tonnes"
  },
  {
    "country": "Poland",
    "capital": "Warsaw",
    "population": 37560000,
    "gdp": "914.70 billion (USD)",
    "area": "92,212 km2",
    "coordinates": "51.9194 N, 19.1451 E",
    "official_languages": "Polish",
    "currency": "Polish Zloty (PLN)",
    "country_code": "+48",
    "religion": "Christianity",
    "elevation": "173 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Portugal",
    "capital": "Lisbon",
    "population": 10380000,
    "gdp": "308.68 billion (USD)",
    "area": "92,212 km2",
    "coordinates": "39.3999 N, 8.2245 W",
    "official_languages": "Portuguese",
    "currency": "Euro (EUR)",
    "country_code": "+351",
    "religion": "Christianity",
    "elevation": "372 m",
    "gold_reserves": "382.66 Tonnes"
  },
  {
    "country": "Qatar",
    "capital": "Doha",
    "population": 2931000,
    "gdp": "217.98 billion (USD)",
    "area": "11,637 km2",
    "coordinates": "25.3548 N, 51.1839 E",
    "official_languages": "Arabic",
    "currency": "Qatari Riyal (QAR)",
    "country_code": "+974",
    "religion": "Islam",
    "elevation": "28 m",
    "gold_reserves": "109.54 Tonnes"
  },
  {
    "country": "Romania",
    "capital": "Bucharest",
    "population": 18518000,
    "gdp": "384.15 billion (USD)",
    "area": "238,397 km2",
    "coordinates": "45.9432 N, 24.9668 E",
    "official_languages": "Romanian",
    "currency": "Romanian Leu (RON)",
    "country_code": "+40",
    "religion": "Christianity",
    "elevation": "414 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Russia",
    "capital": "Moscow",
    "population": 143000000,
    "gdp": "2.2 trillion (USD)",
    "area": "17,125,191 km2",
    "coordinates": "61.5240 N, 105.3188 E",
    "official_languages": "Russian",
    "currency": "Russian Ruble (RUB)",
    "country_code": "+7",
    "religion": "Russian Orthodoxy",
    "elevation": "600 m",
    "gold_reserves": "2,299 Tonnes"
  },
  {
    "country": "Rwanda",
    "capital": "Kigali",
    "population": 14569341,
    "gdp": "14.25 billion (USD)",
    "area": "26,338 km2",
    "coordinates": "1.9403 S, 29.8739 E",
    "official_languages": "Kinyarwanda, French, English",
    "currency": "Rwandan Franc (RWF)",
    "country_code": "+250",
    "religion": "Christianity",
    "elevation": "1,598 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Saint Kitts and Nevis",
    "capital": "Basseterre",
    "population": 46890,
    "gdp": "1,055,499,778 (USD)",
    "area": "174 km2",
    "coordinates": "17.3578 N, 62.7830 W",
    "official_languages": "English",
    "currency": "East Caribbean Dollar (XCD)",
    "country_code": "+1-869",
    "religion": "Christianity",
    "elevation": "578 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Saint Lucia",
    "capital": "Castries",
    "population": 180149,
    "gdp": "2.55 billion (USD)",
    "area": "616 km2",
    "coordinates": "13.9094 N, 60.9789 W",
    "official_languages": "English",
    "currency": "East Caribbean Dollar (XCD)",
    "country_code": "+1-758",
    "religion": "Christianity",
    "elevation": "475 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Samoa",
    "capital": "Apia",
    "population": 219306,
    "gdp": "1.07 billion (USD)",
    "area": "2,842 km2",
    "coordinates": "13.7590 S, 172,1046 W",
    "official_languages": "English",
    "currency": "Samoan Tala (WST)",
    "country_code": "+685",
    "religion": "Christianity",
    "elevation": "929 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "San Martino",
    "capital": "San Marino",
    "population": 33576,
    "gdp": "1,831,700,577(USD)",
    "area": "61 km2",
    "coordinates": "43.9424 N, 12.4578 E",
    "official_languages": "Italian",
    "currency": "Euro (EUR)",
    "country_code": "+378",
    "religion": "Christianity",
    "elevation": "433 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Sao Tome and Principe",
    "capital": "Sao Tome",
    "population": 240254,
    "gdp": "678,976,265 (USD)",
    "area": "964 km2",
    "coordinates": "0.1864 N, 6.6131 E",
    "official_languages": "Portuguese",
    "currency": "Sao Tome and Principe Dobra (STN)",
    "country_code": "+239",
    "religion": "Christianity",
    "elevation": "6 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Saudi Arabia",
    "capital": "Riyadh",
    "population": 34316811,
    "gdp": "1.238 trillion (USD)",
    "area": "2,149,690 km2",
    "coordinates": "23.8859 N, 45.0792 E",
    "official_languages": "Arabic",
    "currency": "Saudi Riyal (SAR)",
    "country_code": "+966",
    "religion": "Islam",
    "elevation": "665 m",
    "gold_reserves": "323.07 Tonnes"
  },
  {
    "country": "Senegal",
    "capital": "Dakar",
    "population": 18753535,
    "gdp": "32.27 billion (USD)",
    "area": "196,722 km2",
    "coordinates": "14.4974 N, 14.4524 W",
    "official_languages": "French",
    "currency": "West African CFA Franc (XOF)",
    "country_code": "+221",
    "religion": "Islam",
    "elevation": "69 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Seychelles",
    "capital": "Victoria",
    "population": 100060,
    "gdp": "2.17 billion (USD)",
    "area": "88,361 km2",
    "coordinates": "4.6796 S, 55.4920 E",
    "official_languages": "French, English",
    "currency": "Seychellois Rupee (SCR)",
    "country_code": "+248",
    "religion": "Christianity",
    "elevation": "905 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Serbia",
    "capital": "Belgrade",
    "population": 6689039,
    "gdp": "92 billion (USD)",
    "area": "88,361 km2",
    "coordinates": "44.0165 N, 21.0059 E",
    "official_languages": "Serbian",
    "currency": "Serbian Dinar (RSD)",
    "country_code": "+381",
    "religion": "Christianity",
    "elevation": "442 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Sierra Leone",
    "capital": "Freetown",
    "population": 8819794,
    "gdp": "7.55 billion (USD)",
    "area": "71,740 km2",
    "coordinates": "8.4606 N, 11.7799 W",
    "official_languages": "English",
    "currency": "Sierra Leonean Leone (SLE)",
    "country_code": "+232",
    "religion": "Islam/Christianity",
    "elevation": "279 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Singapore",
    "capital": "Singapore",
    "population": 5870750,
    "gdp": "547.39 billion (USD)",
    "area": "750 km2",
    "coordinates": "1.3521 N, 103.8198 E",
    "official_languages": "Malay, English, Tamil,Mandarin",
    "currency": "Singapore Dollar (SGD)",
    "country_code": "+65",
    "religion": "Buddhism",
    "elevation": "15 m",
    "gold_reserves": "227.61 Tonnes"
  },
  {
    "country": "Slovakia",
    "capital": "Bratislava",
    "population": 5474881,
    "gdp": "141.78 billion (USD)",
    "area": "49,035 km2",
    "coordinates": "48.6690 N, 19.6990 E",
    "official_languages": "Slovak",
    "currency": "Euro (EUR)",
    "country_code": "+421",
    "religion": "Christianity",
    "elevation": "458 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Slovenia",
    "capital": "Ljubljana",
    "population": 2117739,
    "gdp": "72.49 billion (USD)",
    "area": "20,271 km2",
    "coordinates": "46.1512 N, 14.9955 E",
    "official_languages": "Slovenian",
    "currency": "Euro (EUR)",
    "country_code": "+386",
    "religion": "Christianity",
    "elevation": "492 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Solomon Islands",
    "capital": "Honiara",
    "population": 830572,
    "gdp": "1.76 billion (USD)",
    "area": "28,896 km2",
    "coordinates": "9.5529 S, 160.1562 E",
    "official_languages": "English",
    "currency": "Solomon Islands Dollar (SBD)",
    "country_code": "+677",
    "religion": "Christianity",
    "elevation": "2,335 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Somalia",
    "capital": "Mogadishu",
    "population": 19654739,
    "gdp": "12.11 billion (USD)",
    "area": "637,657 km2",
    "coordinates": "5.1521 N, 46.1996 E",
    "official_languages": "Somali, Arabic",
    "currency": "Somali Shilling (SOS)",
    "country_code": "+252",
    "religion": "Islam",
    "elevation": "410 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "South Africa",
    "capital": "Bloemfontein",
    "population": 64747319,
    "gdp": "410 billion (USD)",
    "area": "1,221,037 km2",
    "coordinates": "30.5595 S, 22.9375 E",
    "official_languages": "Afrikaans, English",
    "currency": "South African Rand (ZAR)",
    "country_code": "+27",
    "religion": "Christianity",
    "elevation": "1,034 m",
    "gold_reserves": "125.44 Tonnes"
  },
  {
    "country": "South Korea",
    "capital": "Seoul",
    "population": 51690479,
    "gdp": "1,712.79 billion (USD)",
    "area": "100,363 km2",
    "coordinates": "35.9078 N, 127.7669 E",
    "official_languages": "Korean",
    "currency": "South Korean WOn (KRW)",
    "country_code": "+82",
    "religion": "Buddhism/Christianity",
    "elevation": "282 m",
    "gold_reserves": "104.45 Tonnes"
  },
  {
    "country": "South Sudan",
    "capital": "Juba",
    "population": 12188788,
    "gdp": "5.42 billion (USD)",
    "area": "644,329 km2",
    "coordinates": "6.8770 N, 31.3070 E",
    "official_languages": "English",
    "currency": "South Sudanese Pound (SSP)",
    "country_code": "+211",
    "religion": "Christianity",
    "elevation": "3,362 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Spain",
    "capital": "Madrid",
    "population": 47889958,
    "gdp": "1.72 trillion (USD)",
    "area": "506,030 km2",
    "coordinates": "40.4637 N, 3.7492 W",
    "official_languages": "Spanish",
    "currency": "Euro (EUR)",
    "country_code": "+34",
    "religion": "Christianity",
    "elevation": "660 m",
    "gold_reserves": "281.58 Tonnes"
  },
  {
    "country": "Sri Lanka",
    "capital": "Colombo",
    "population": 23229470,
    "gdp": "98.96 billion (USD)",
    "area": "65,612 km2",
    "coordinates": "7.8731 N, 80.7718 E",
    "official_languages": "Sinhala, Tamil",
    "currency": "Sri Lankan Rupee (LKR)",
    "country_code": "+94",
    "religion": "Buddhism",
    "elevation": "228 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "St. Vincent Grenadines",
    "capital": "Kingstown",
    "population": 99924,
    "gdp": "1.16 billion (USD)",
    "area": "344 km2",
    "coordinates": "13.2528 N, 61.1971 W",
    "official_languages": "English",
    "currency": "East Caribbean Dollar (XCD)",
    "country_code": "+1-784",
    "religion": "Christianity",
    "elevation": "617 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "State of Palestine",
    "capital": "East Jerusalem",
    "population": 5589623,
    "gdp": "13.71 billion (USD)",
    "area": "6,020 km2",
    "coordinates": "31.9522 N, 35.2332 E",
    "official_languages": "Arabic",
    "currency": "No official currency",
    "country_code": "+970",
    "religion": "Islam",
    "elevation": "74 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Sudan",
    "capital": "Khartoum",
    "population": 51662147,
    "gdp": "49.91 billion (USD)",
    "area": "1,886,000 km2",
    "coordinates": "12.8628 N, 30.2176 E",
    "official_languages": "Arabic,English",
    "currency": "Sudanese Pound (SDG)",
    "country_code": "+249",
    "religion": "Islam",
    "elevation": "568 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Suriname",
    "capital": "Paramaribo",
    "population": 618040,
    "gdp": "4.71 billion (USD)",
    "area": "163,820 km2",
    "coordinates": "3.9193 N, 56.0278 W",
    "official_languages": "Dutch",
    "currency": "Surinamese Dollar (SRD)",
    "country_code": "+597",
    "religion": "Christianity",
    "elevation": "246 m",
    "gold_reserves": "1.21 Tonnes"
  },
  {
    "country": "Sweden",
    "capital": "Stockholm",
    "population": 10656633,
    "gdp": "610.12 billion (USD)",
    "area": "450,295 km2",
    "coordinates": "60.1282 N, 18.6435 E",
    "official_languages": "Swedish",
    "currency": "Swedish Krona (SEK)",
    "country_code": "+46",
    "religion": "Christianity",
    "elevation": "320 m",
    "gold_reserves": "125.72 Tonnes"
  },
  {
    "country": "Switzerland",
    "capital": "Bern",
    "population": 8967407,
    "gdp": "936.56 billion (USD)",
    "area": "41,285 km2",
    "coordinates": "46.8182 N 8.2275 E",
    "official_languages": "German, French, Italian,Romansh",
    "currency": "Swiss Franc (CHF)",
    "country_code": "+41",
    "religion": "Christianity",
    "elevation": "1,350 m",
    "gold_reserves": "1,039.94 Tonnes"
  },
  {
    "country": "Syria",
    "capital": "Damascus",
    "population": 25620427,
    "gdp": "19.99 billion (USD)",
    "area": "185,180 km2",
    "coordinates": "34.8021 N, 38.9968 E",
    "official_languages": "Arabic",
    "currency": "Syrian Pound (SYP)",
    "country_code": "+963",
    "religion": "Islam",
    "elevation": "514 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Tajikistan",
    "capital": "Turkistan",
    "population": 9950000,
    "gdp": "14.20 billion (USD)",
    "area": "143,000 km2",
    "coordinates": "38.8610 N, 71.2761 E",
    "official_languages": "Tajiki, Russian",
    "currency": "Tajikistani Somoni (TJS)",
    "country_code": "+992",
    "religion": "Islam",
    "elevation": "3,186 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Tanzania",
    "capital": "Hobart",
    "population": 70545865,
    "gdp": "78.78 billion (USD)",
    "area": "947,300 km2",
    "coordinates": "6.3690 S, 34.8888 E",
    "official_languages": "Swahili, English",
    "currency": "Tanzanian Shilling (TZS)",
    "country_code": "+255",
    "religion": "Christianity",
    "elevation": "1,018 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Thailand",
    "capital": "Bangkok",
    "population": 71619863,
    "gdp": "526.41 billion (USD)",
    "area": "513,120 km2",
    "coordinates": "15.8700 N, 100.9925 E",
    "official_languages": "Central Thai",
    "currency": "Thai Baht (THB)",
    "country_code": "+66",
    "religion": "Buddhism",
    "elevation": "287 m",
    "gold_reserves": "234.52 Tonnes"
  },
  {
    "country": "Timor-Leste",
    "capital": "Dili",
    "population": 1418517,
    "gdp": "2.02 billion (USD)",
    "area": "14,874 km2",
    "coordinates": "8.8742 S, 125.7275 E",
    "official_languages": "Portuguese, Tetum",
    "currency": "United States Dollar (USD)",
    "country_code": "+670",
    "religion": "Christianity",
    "elevation": "1,482 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Togo",
    "capital": "Lome",
    "population": 9470157,
    "gdp": "2.02 billion (USD)",
    "area": "56,785 km2",
    "coordinates": "8.6195 N, 0.8248 E",
    "official_languages": "French",
    "currency": "West African CFA Franc (XOF)",
    "country_code": "+228",
    "religion": "Christianity",
    "elevation": "236 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Tonga",
    "capital": "Nukualofa",
    "population": 103742,
    "gdp": "0.51 billion (USD)",
    "area": "750 km2",
    "coordinates": "21.1790 S, 175.1982 W",
    "official_languages": "Tongan, English",
    "currency": "Tongan Pa'anga (TOP)",
    "country_code": "+676",
    "religion": "Christianity",
    "elevation": "517 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Trinidad and Tobago",
    "capital": "Port of Spain",
    "population": 1511155,
    "gdp": "26.43 billion (USD)",
    "area": "5131 km2",
    "coordinates": "10.6918 N, 61.2225 W",
    "official_languages": "English",
    "currency": "Trinidad and Tobago Dollar (TTD)",
    "country_code": "+1-868",
    "religion": "Christianity",
    "elevation": "83 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Tunisia",
    "capital": "Tunis",
    "population": 12348573,
    "gdp": "53.41 billion (USD)",
    "area": "163,610 km2",
    "coordinates": "33.8869 N, 9.5375 E",
    "official_languages": "Arabic",
    "currency": "Tunisian Dinar (TND)",
    "country_code": "+216",
    "religion": "Islam",
    "elevation": "246 m",
    "gold_reserves": "6.84 Tonnes"
  },
  {
    "country": "Turkey",
    "capital": "Ankara",
    "population": 87685426,
    "gdp": "1,323.25 billion (USD)",
    "area": "783,356 km2",
    "coordinates": "38.9637 N, 35.2433 E",
    "official_languages": "Turkish",
    "currency": "Turkish Lira (TRY)",
    "country_code": "+90",
    "religion": "Islam",
    "elevation": "1,141 m",
    "gold_reserves": "583 Tonnes"
  },
  {
    "country": "Turkmenistan",
    "capital": "Ashgabat",
    "population": 7618847,
    "gdp": "64.24 billion (USD)",
    "area": "491,210 km2",
    "coordinates": "38.9697 N, 59.5563 E",
    "official_languages": "Turkmen",
    "currency": "Turkmenistani Manat (TMT)",
    "country_code": "+993",
    "religion": "Islam",
    "elevation": "230 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Tuvalu",
    "capital": "Funafuti",
    "population": 12141,
    "gdp": "62,280,312 (USD)",
    "area": "26.26 km2",
    "coordinates": "7.1095 S, 177.6493 E",
    "official_languages": "Tuvaluan, English",
    "currency": "Tuvaluan Dollar (TVD)",
    "country_code": "+688",
    "religion": "Christianity",
    "elevation": "4.6m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Uganda",
    "capital": "Kampala",
    "population": 51384894,
    "gdp": "53.65 billion (USD)",
    "area": "200,520 km2",
    "coordinates": "1.3733 N, 32.2903 E",
    "official_languages": "English, Swahili",
    "currency": "Ugandan Shilling (UGX)",
    "country_code": "+256",
    "religion": "Christianity",
    "elevation": "1,100 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Ukraine",
    "capital": "Kyiv",
    "population": 38980376,
    "gdp": "190.74 billion (USD)",
    "area": "603,628 km2",
    "coordinates": "48.3794 N, 31.1656 E",
    "official_languages": "Ukrainian",
    "currency": "Ukrainian Hryvnia (UAH)",
    "country_code": "+380",
    "religion": "Christianity",
    "elevation": "175 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "UAE",
    "capital": "Abu Dhabi",
    "population": 11346000,
    "gdp": "537 billion (USD)",
    "area": "83,600 km2",
    "coordinates": "23.4241 N, 53.8478 E",
    "official_languages": "Arabic",
    "currency": "United Arab Emirates Dirham (AED)",
    "country_code": "+971",
    "religion": "Islam",
    "elevation": "149 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "United Kingdom",
    "capital": "London",
    "population": 69551332,
    "gdp": "3.6 trillion (USD)",
    "area": "243,610 km2",
    "coordinates": "55.3781 N, 3.4360 W",
    "official_languages": "English",
    "currency": "Pound Sterling (GBP)",
    "country_code": "+44",
    "religion": "Christianity",
    "elevation": "162 m",
    "gold_reserves": "310 Tonnes"
  },
  {
    "country": "United States of America",
    "capital": "Washington DC",
    "population": 347275807,
    "gdp": "30.486 trillion (USD)",
    "area": "9,147,420 km2",
    "coordinates": "38.7946 N, 106.5348 W",
    "official_languages": "English",
    "currency": "United States Dollar (USD)",
    "country_code": "+1",
    "religion": "Christianity",
    "elevation": "760 m",
    "gold_reserves": "8,133 Tonnes"
  },
  {
    "country": "Uruguay",
    "capital": "Montevideo",
    "population": 3384688,
    "gdp": "80.96 billion (USD)",
    "area": "176,215 km2",
    "coordinates": "32.5228 S, 55.7658 W",
    "official_languages": "Spanish",
    "currency": "Uruguayan Peso (UYU)",
    "country_code": "+598",
    "religion": "Christianity",
    "elevation": "109 m",
    "gold_reserves": "0.10 Tonnes"
  },
  {
    "country": "Uzbekistan",
    "capital": "Tashkent",
    "population": 37053428,
    "gdp": "114.97 billion (USD) ",
    "area": "447,400 km2",
    "coordinates": "41.3775 N, 64.5853 E",
    "official_languages": "Uzbek",
    "currency": "Uzbekistani SOm (UZS)",
    "country_code": "+998",
    "religion": "Islam",
    "elevation": "450 m",
    "gold_reserves": "373.86 Tonnes"
  },
  {
    "country": "Vanuatu",
    "capital": "Port Villa",
    "population": 326740,
    "gdp": "1.16 billion (USD)",
    "area": "12,189 km2",
    "coordinates": "15.3767 S, 166.9592 E",
    "official_languages": "Bislama, English, French",
    "currency": "Vatu (VUV)",
    "country_code": "+678",
    "religion": "Christianity",
    "elevation": "1,877 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Venezuela",
    "capital": "Caracas",
    "population": 28516896,
    "gdp": "111.81 billion (USD)",
    "area": "912,050 km2",
    "coordinates": "6.4238 N, 66.5897 W",
    "official_languages": "Spanish",
    "currency": "Venezuelan Bolivar (VES)",
    "country_code": "+58",
    "religion": "Christianity",
    "elevation": "450 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Vietnam",
    "capital": "Hanoi",
    "population": 101598527,
    "gdp": "476.39 billion (USD)",
    "area": "331,211 km2",
    "coordinates": "14.0583 N, 108.2772 E",
    "official_languages": "Vietnamese",
    "currency": "Vietnamese Dong (VND)",
    "country_code": "84",
    "religion": "Buddhism",
    "elevation": "398 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Yemen",
    "capital": "Sana'a",
    "population": 41773878,
    "gdp": "19.10 billion (USD)",
    "area": "527,970 km2",
    "coordinates": "15.5527 N, 48.5164 E",
    "official_languages": "Arabic",
    "currency": "Yemeni Rial (YER)",
    "country_code": "+967",
    "religion": "Islam",
    "elevation": "999 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Zambia",
    "capital": "Lusaka",
    "population": 20020000,
    "gdp": "26.33 billion (USD)",
    "area": "752,618 km2",
    "coordinates": "13.1339 S, 27.8493 E",
    "official_languages": "Bemba, Nyanja, Lozi, Tonga, Luvale, Lunda, and Kaonde",
    "currency": "Zambian Kwacha (ZMW)",
    "country_code": "+260",
    "religion": "Christianity",
    "elevation": "1,138 m",
    "gold_reserves": "low/Negligible"
  },
  {
    "country": "Zimbabwe",
    "capital": "Harare",
    "population": 16950795,
    "gdp": "45.7 billion (USD)",
    "area": "386,850 km2",
    "coordinates": "19.0154 S, 29.1549 E",
    "official_languages": "Shona, English, Xhosa, Chewa,Tshwa, Southern Sotho",
    "currency": "Zimbabwean Dollar (ZWL)",
    "country_code": "+263",
    "religion": "Christianity",
    "elevation": "961 m",
    "gold_reserves": "low/Negligible"
  }
];
